alias rm='rm -i'
alias l='ls -la'
alias c='clear'
alias sc='systemctl'

#docker_utils_alias
alias dex='docker exec -it'
alias  dimg='docker images'
alias  dps='docker ps'
alias  dpsa='docker ps -a'
alias  drm='docker rm'
alias  drmi='docker rmi'
alias  dstart='docker start'
alias  dstop='docker stop'
alias  drestart='docker restart'
alias  dstats='docker stats --no-stream'
alias  dlogs='docker logs -f'
alias  dtag='docker tag'
alias  dren='docker rename'
alias  dpull='docker pull'
alias  dpush='docker push'
alias  dsch='docker search'
