version: '3.9'

services:
  proxy:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    container_name: nginx
    restart: always
    privileged: true
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot:ro
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf:/etc/letsencrypt/:rw
    command: certonly --webroot -w /var/www/certbot --force-renewal --email $email -d $domain --agree-tos

networks:
  default:
    name: $network
    external: true